### PR TITLE
Tweak script to work for Windows environment (closes #32)

### LINKED ISSUE #32: Builder doesn't work on Windows
All the previous development work has been done on an `Ubuntu` VM, which has worked perfectly fine.

However, trying to run the `test.js` build script on a Windows machine gives a number of errors...

### PR DESCRIPTION
**Pull request by rugulous**
Does what it says on the tin, closes #32

### CODE REVIEW

File: build/Builder.js [hunk 1]
```diff
@@ -4,22 +4,22 @@ const sass = require('sass');
...
-	setVariable(name, value){
+	setVariable(name, value) {
 		this.vars[name] = value;
 		return this; //allow chaining
 	}
 
-	getVariables(){
-		const varString = Object.values(this.vars).map((k, v) => `$${k}: ${v};` ).join("\n");
+	getVariables() {
+		const varString = Object.entries(this.vars).map(arr => `$${arr[0]}: ${arr[1]};`).join("\n");
```
Comment (matt-fidd) [inline build/Builder.js]: This works, but it could be made cleaner with array destructuring. 

`map([k, v] =>... ` 

If wanted, happy to merge as is just thought I'd mention it.

Comment (rugulous) [reply build/Builder.js]: Good spot, didn't even cross my mind!

**Review by matt-fidd — APPROVED** [review]
